language: objective-c
cache:
  directories:
  - /Library/Caches/Homebrew
  - .m2
install:
  - brew update && brew tap facebook/fb
  - brew install buck leiningen phantomjs planck
script:
  - buck build "//..." && buck test "//..."
