language: objective-c
cache:
  directories:
  - /Library/Caches/Homebrew
  - .m2
install:
  - brew update
  - brew install https://raw.githubusercontent.com/facebook/homebrew-fb/master/buck.rb
  - brew install leiningen
  - brew install phantomjs
script:
  - buck build "//..." | tee /dev/null && buck test "//..." | tee /dev/null
