language: objective-c
cache:
  directories:
  - /Library/Caches/Homebrew
  - .m2
install:
  - brew install https://raw.githubusercontent.com/facebook/homebrew-fb/master/buck.rb
  - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/leiningen.rb
  - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/phantomjs.rb
script:
  - buck build "//..." | tee /dev/null && buck test "//..." | tee /dev/null
