language: objective-c
cache:
  directories:
  - /Library/Caches/Homebrew
  - .m2
install:
  - brew update
  - brew install https://raw.githubusercontent.com/facebook/homebrew-fb/bf709a69b61a4bb776433be1fce675a66a8644f2/buck.rb
  - brew install leiningen
  - brew install phantomjs
script:
  - buck build "//..." | tee /dev/null && buck test "//..." | tee /dev/null
