language: objective-c
cache:
  directories:
  - /Library/Caches/Homebrew
  - .m2
install:
  - brew update && brew tap facebook/fb
  - brew install buck leiningen phantomjs planck
script:
  - mv tests/BUCK.tests tests/BUCK
  - mv clj-cljs-config/BUCK.example clj-cljs-config/BUCK
  - TERM=dumb buck build "//..." && buck test "//..."
