for dep in [# Default dependencies
            'org.clojure/clojure 1.8.0',
            'org.clojure/clojurescript 1.9.89',
            # CLJS specifics
            'figwheel-sidecar 0.5.4-7',
            'com.cemerick/piggieback 0.2.1',
            'lein-doo 0.1.6',
            # For testing
            'org.clojure/data.json 0.2.6',
            'aleph 0.4.1-beta2',
            'org.omcljs/om 1.0.0-alpha28']:
    ext_dep(dep)
