export_file(name = 'build.cljs',
            out = 'build.cljs',
            visibility = ['PUBLIC'])

genrule(name = 'builder',
        srcs = [],
        # HACK: If we change `build.cljs` file then `build` target would be updated, but because
        # it will generate exactly the same output (planck script invocation is the same) then
        # no rebuild will occur for dependent targets. Here we force it by including md5 checksum
        # into the script file as a comment
        bash = 'echo "planck $(location //RULES/clj-cljs:build.cljs) \$@" > $OUT && ' +
               'echo "#`cat $(location //RULES/clj-cljs:build.cljs) | md5`" >> $OUT && ' +
               'chmod +x $OUT',
        out = 'build.sh',
        executable = True,
        visibility = ['PUBLIC'])
